sudo: false
language: python
cache:
    directories:
        - $HOME/.cache/pip
matrix:
    include:
        - python: 2.6 # these are just to make travis's UI a bit prettier
          env: TOXENV=py26
        - python: 2.7
          env: TOXENV=py27
        - python: 3.3
          env: TOXENV=py33
        - python: 3.4
          env: TOXENV=py34
        - python: pypy
          env: TOXENV=pypy
        - python: 2.6
          env: TOXENV=py26 OPENSSL=0.9.8
          addons:
              apt:
                  sources:
                      - lucid
                  packages:
                      - libssl-dev/lucid
        - python: 2.7
          env: TOXENV=py27 OPENSSL=0.9.8
          addons:
              apt:
                  sources:
                      - lucid
                  packages:
                      - libssl-dev/lucid
        - python: 3.3
          env: TOXENV=py33 OPENSSL=0.9.8
          addons:
              apt:
                  sources:
                      - lucid
                  packages:
                      - libssl-dev/lucid
        - python: 3.4
          env: TOXENV=py34 OPENSSL=0.9.8
          addons:
              apt:
                  sources:
                      - lucid
                  packages:
                      - libssl-dev/lucid
        - python: pypy
          env: TOXENV=pypy OPENSSL=0.9.8
          addons:
              apt:
                  sources:
                      - lucid
                  packages:
                      - libssl-dev/lucid
        - python: 2.7
          env: TOXENV=docs
          addons:
              apt:
                  packages:
                      - libenchant-dev
        - python: 2.7
          env: TOXENV=pep8
        - python: 3.3
          env: TOXENV=py3pep8
        - language: generic
          os: osx
          env: TOXENV=py26
        - language: generic
          os: osx
          env: TOXENV=py27
        - language: generic
          os: osx
          env: TOXENV=py33
        - language: generic
          os: osx
          env: TOXENV=py34
        - language: generic
          os: osx
          env: TOXENV=pypy
        - language: generic
          os: osx
          env: TOXENV=pypy3
        - language: generic
          os: osx
          env: TOXENV=py26 OPENSSL=0.9.8
        - language: generic
          os: osx
          env: TOXENV=py27 OPENSSL=0.9.8
        - language: generic
          os: osx
          env: TOXENV=py33 OPENSSL=0.9.8
        - language: generic
          os: osx
          env: TOXENV=py34 OPENSSL=0.9.8
        - language: generic
          os: osx
          env: TOXENV=pypy OPENSSL=0.9.8
        - language: generic
          os: osx
          env: TOXENV=pypy3 OPENSSL=0.9.8
        - language: generic
          os: osx
          env: TOXENV=docs

install:
    - ./.travis/install.sh

script:
    - ./.travis/run.sh

after_success:
    - bash <(curl -s https://raw.githubusercontent.com/codecov/codecov-bash/coveragepy/codecov) -e TRAVIS_OS_NAME,TOXENV,OPENSSL

notifications:
    irc:
        channels:
            - "irc.freenode.org#cryptography-dev"
        use_notice: true
        skip_join: true
    webhooks:
        - https://buildtimetrend.herokuapp.com/travis
